# CodeDeploy 버전을 의미
# 프로젝트 버전이 아니므로 0.0 외에 다른 버전을 사용하면 오류 발생
version: 0.0
os: linux
files:
  - source: / # CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상을 지정합니다. 루트경로는 전체를 의미 합니다.
    destination: /home/ec2-user/app/step2/zip
    overwrite: yes

permissions: # CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 함
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:  # CodeDeploy 배포 단계에서 실행할 명령어를 지정합니다.
  ApplicationStart: # 여기선 ec2-user권한으로 deploy.sh 실행
    - location: deploy.sh
      timeout: 60 # 60초 동안 배포되지 못하면 실패
      runas: ec2-user
